name: 'Agentic Code Sec Reviewer'
description: '该Agent首先使用codeql等工具对PR中的代码进行安全扫描，然后使用基于RAG的多智能体系统对扫描结果进行研判，并将真正的安全问题以评论的形式反馈到PR中。'
author: 'lnjoy'

inputs:
  github_token:
    description: '用于发表 PR 评论的 GITHUB_TOKEN'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
      
    - name: Install python dependencies
      shell: bash
      run: |
        pip install -r ${{ github.action_path }}/requirements.txt

    - name: Detect Primary Language
      shell: bash
      run: |
        echo "Starting language detection..."
        DETECTED_LANGUAGE=""
        BUILD_MODE="none" # 为提高速度，对java等编译型语言不进行编译分析

        if [ -f "pom.xml" ] || [ -f "build.gradle" ] || [ -f "build.gradle.kts" ]; then
            DETECTED_LANGUAGE="java"
            echo "Detected Java build file."
        elif [ -f "go.mod" ]; then
            DETECTED_LANGUAGE="go"
            BUILD_MODE="autobuild" # Go 目前还不支持build-mode: none，必须使用 autobuild
            echo "Detected Go module file."
        elif [ -f "requirements.txt" ] || [ -f "pyproject.toml" ] || [ -f "setup.py" ] || [ -f "Pipfile" ]; then
            DETECTED_LANGUAGE="python"
            echo "Detected Python configuration file."
        else
            echo "Error: Currently supported languages only include Python, Java, and Go."
            exit 1
        fi

        echo "LANGUAGE=$DETECTED_LANGUAGE" >> $GITHUB_ENV
        echo "BUILD_MODE=$BUILD_MODE" >> $GITHUB_ENV

    - name: Install Trivy
      shell: bash
      run: |
        echo "Installing Trivy..."
        curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin

    - name: Install Gitleaks
      shell: bash
      run: |
        echo "Installing Gitleaks..."
        VERSION=$(curl -s https://api.github.com/repos/gitleaks/gitleaks/releases/latest | grep '"tag_name":' | sed -E 's/.*"v([^"]+)".*/\1/')
        wget https://github.com/gitleaks/gitleaks/releases/download/v${VERSION}/gitleaks_${VERSION}_linux_x64.tar.gz
        tar -zxvf gitleaks_${VERSION}_linux_x64.tar.gz
        sudo mv gitleaks /usr/local/bin/

    - name: Install Semgrep
      shell: bash
      run: |
        echo "Installing Semgrep..."
        python3 -m pip install semgrep

    - name: Install CodeQL
      shell: bash
      run: |
        wget https://github.com/github/codeql-action/releases/latest/download/codeql-bundle-linux64.tar.gz
        tar -xvzf codeql-bundle-linux64.tar.gz
        echo "$(pwd)/codeql" >> $GITHUB_PATH

    # - name: Initialize CodeQL
    #   uses: github/codeql-action/init@v3
    #   with:
    #     languages: ${{ env.LANGUAGE }}
    #     queries: security-extended
    #     build-mode: ${{ env.BUILD_MODE }}

    # - name: Perform CodeQL Analysis
    #   uses: github/codeql-action/analyze@v3
    #   with:
    #     upload: false
    #     output: ${{ github.workspace }}/sarif-results # 将sarif结果保存到这个文件夹

    - name: Cache Trivy DB
      uses: actions/cache@v3
      with:
        path: /tmp/trivy_cache
        key: ${{ runner.os }}-trivy-db-${{ github.run_id }}
        restore-keys: |
          ${{ runner.os }}-trivy-db-

    - name: Run code review
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        BASE_SHA: ${{ github.event.pull_request.base.sha }}
        HEAD_SHA: ${{ github.event.pull_request.head.sha }}
        CODEQL_RESULTS_DIR: ${{ github.workspace }}/sarif-results
      run: |
        python ${{ github.action_path }}/main.py