INJECTION_CWES = [
    "cwe-22",   # 路径穿越 (Path Traversal)
    "cwe-74",   # 注入漏洞的通用父类 (Injection)
    "cwe-77",   # 命令注入通用父类 (Command Injection)
    "cwe-78",   # 操作系统命令注入 (OS Command Injection)
    "cwe-79",   # 跨站脚本攻击 (XSS)
    "cwe-89",   # SQL注入 (SQL Injection)
    "cwe-90",   # LDAP注入 (LDAP Injection)
    "cwe-94",   # 代码注入 (Code Injection)
    "cwe-502",  # 反序列化漏洞 (Deserialization of Untrusted Data)
    "cwe-611",  # XML外部实体注入 (XXE)
    "cwe-643",  # XPath注入 (XPath Injection)
    "cwe-918",  # 服务器端请求伪造 (SSRF)
    "cwe-943",  # NoSQL注入 (NoSQL Injection)
    "cwe-1336"  # 模板注入 (Template Injection / SSTI)
]

LOGIC_IDENTITY_CWES = [
    "cwe-269",  # 不恰当的特权管理 (Improper Privilege Management - 垂直越权/提权)
    "cwe-284",  # 不恰当的访问控制 (Improper Access Control - 越权通用)
    "cwe-285",  # 不恰当的授权 (Improper Authorization)
    "cwe-287",  # 不恰当的身份验证 (Improper Authentication - 鉴权绕过/JWT伪造)
    "cwe-288",  # 绕过身份验证 (Authentication Bypass)
    "cwe-306",  # 关键功能缺失身份验证 (Missing Authentication - 未授权访问)
    "cwe-362",  # 并发执行竞争条件 (Race Condition - 条件竞争)
    "cwe-367",  # 检查时与使用时竞争条件 (TOCTOU - Race Condition)
    "cwe-384",  # 会话固定/会话状态问题 (Session/State issues)
    "cwe-488",  # 数据泄露给错误会话 (Context Leakage / 异步上下文污染)
    "cwe-639",  # 不安全的直接对象引用 (IDOR - 越权访问)
    "cwe-696",  # 行为顺序错误 (State Machine Bypass - 状态机绕过)
    "cwe-840",  # 业务逻辑错误 (Business Logic Flaws / 支付漏洞)
    "cwe-862",  # 缺失授权 (Missing Authorization)
    "cwe-863",  # 授权错误 (Incorrect Authorization)
    "cwe-915"   # 动态对象属性的未受控修改 (Mass Assignment - 批量赋值)
]

DATA_ASSET_CWES = [
    "cwe-200",  # 敏感信息暴露给未经授权的参与者 (Exposure of Sensitive Information)
    "cwe-209",  # 生成包含敏感信息的错误消息 (Error Message Containing Sensitive Information)
    "cwe-259",  # 硬编码密码 (Use of Hard-coded Password)
    "cwe-312",  # 敏感信息明文存储 (Cleartext Storage of Sensitive Information)
    "cwe-319",  # 敏感信息明文传输 (Cleartext Transmission of Sensitive Information)
    "cwe-321",  # 硬编码加密密钥 (Use of Hard-coded Cryptographic Key)
    "cwe-327",  # 使用被破坏或有风险的加密算法 (Broken/Risky Crypto Algorithm - 如DES, ECB模式等)
    "cwe-328",  # 可逆的单向哈希 (Reversible One-Way Hash - 如MD5, SHA1)
    "cwe-329",  # 密码块链接模式未使用随机IV (Not Using a Random IV with CBC Mode)
    "cwe-330",  # 使用了不可靠的随机值 (Use of Insufficiently Random Values)
    "cwe-331",  # 熵不足 (Insufficient Entropy)
    "cwe-338",  # 使用了密码学上较弱的伪随机数生成器 (Cryptographically Weak PRNG - 如Python的 random 模块)
    "cwe-532",  # 日志文件中包含敏感信息 (Insertion of Sensitive Information into Log File)
    "cwe-540",  # 源代码中包含敏感信息 (Inclusion of Sensitive Information in Source Code)
    "cwe-780",  # RSA算法未使用OAEP填充 (Use of RSA Algorithm without OAEP)
    "cwe-798",  # 硬编码凭据通用类 (Use of Hard-coded Credentials)
    "cwe-916",  # 密码哈希的计算强度不足 (Insufficient Computational Effort - 弱KDF如未加盐或迭代次数少)
    "cwe-1204"  # 生成了弱初始化向量IV (Generation of Weak Initialization Vector)
]

INFRA_SUPPLY_CWES = [
    "cwe-16",   # 配置通用类 (Configuration - 泛指各种不安全的框架/应用基线配置)
    "cwe-215",  # 调试代码中插入敏感信息 (Insertion of Sensitive Information Into Debugging Code - 如 Django/Flask 开启 Debug 模式泄露敏感环境信息)
    "cwe-250",  # 以不必要的特权执行 (Execution with Unnecessary Privileges - 如 Docker 容器以 Root 权限运行)
    "cwe-266",  # 权限分配不正确 (Incorrect Privilege Assignment - 赋予容器或节点过高的 Capabilities)
    "cwe-276",  # 不正确的默认权限 (Incorrect Default Permissions - 如安装脚本/镜像构建时的过度赋权)
    "cwe-427",  # 不受控的搜索路径元素 (Uncontrolled Search Path Element - 环境变量劫持，如 PYTHONPATH 污染导致加载恶意模块)
    "cwe-489",  # 活跃的调试代码 (Active Debug Code - 生产环境遗留测试接口或后门工具)
    "cwe-506",  # 嵌入恶意代码 (Embedded Malicious Code - 如第三方依赖投毒/后门)
    "cwe-552",  # 外部可访问的文件或目录 (Files or Directories Accessible to External Parties - 如静态资源配置错误导致源码泄露)
    "cwe-668",  # 暴露资源到错误的控制域 (Exposure of Resource to Wrong Sphere - 如服务意外绑定到 0.0.0.0 导致内网穿透或公网暴露)
    "cwe-732",  # 关键资源的不正确权限分配 (Incorrect Permission Assignment for Critical Resource - 如 Dockerfile 中暴力的 chmod 777)
    "cwe-829",  # 包含来自不受信控制域的功能 (Inclusion of Functionality from Untrusted Control Sphere - 依赖投毒 / 从不受信源拉取包)
    "cwe-937",  # 使用含有已知漏洞的组件 (Using Components with Known Vulnerabilities - 最典型的第三方依赖 CVE 告警)
    "cwe-1104", # 使用未维护的第三方组件 (Use of Unmaintained Third Party Components - 废弃包风险)
    "cwe-1188", # 资源的不安全默认初始化 (Insecure Default Initialization of Resource - 使用框架默认不安全的配置)
    "cwe-1327", # 绑定到不受限制的IP地址 (Binding to an Unrestricted IP Address - 如监听 0.0.0.0 带来的暴露风险)
    "cwe-1357"  # 依赖不可信的组件 (Reliance on Insufficiently Trustworthy Component - 依赖混淆/私有包被公共仓库同名包劫持)
]